// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app_layout from "./routes/(app)/_layout.tsx";
import * as $_app_index from "./routes/(app)/index.tsx";
import * as $_app_portfolio from "./routes/(app)/portfolio.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_abi_address_ from "./routes/api/v1/abi/[address].ts";
import * as $components_Avatar_Avatar from "./islands/components/Avatar/Avatar.tsx";
import * as $components_Button_Button from "./islands/components/Button/Button.tsx";
import * as $components_ModalButton_ModalButton from "./islands/components/ModalButton/ModalButton.tsx";
import * as $components_NewEventModalButton_NewEventModalButton from "./islands/components/NewEventModalButton/NewEventModalButton.tsx";
import * as $components_Pills_PillTick from "./islands/components/Pills/PillTick.tsx";
import * as $components_Pills_Pills from "./islands/components/Pills/Pills.tsx";
import * as $components_SelectInput_SelectInput from "./islands/components/SelectInput/SelectInput.tsx";
import * as $components_Tag_Tag from "./islands/components/Tag/Tag.tsx";
import * as $components_TextInput_TextInput from "./islands/components/TextInput/TextInput.tsx";
import * as $components_WalletButton_WalletButton from "./islands/components/WalletButton/WalletButton.tsx";
import * as $pages_Markets_MarketCard from "./islands/pages/Markets/MarketCard.tsx";
import * as $pages_Markets_Markets from "./islands/pages/Markets/Markets.tsx";
import * as $pages_Markets_formatCurrencyShort from "./islands/pages/Markets/formatCurrencyShort.ts";
import * as $pages_Portfolio_Portfolio from "./islands/pages/Portfolio/Portfolio.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(app)/_layout.tsx": $_app_layout,
    "./routes/(app)/index.tsx": $_app_index,
    "./routes/(app)/portfolio.tsx": $_app_portfolio,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/abi/[address].ts": $api_v1_abi_address_,
  },
  islands: {
    "./islands/components/Avatar/Avatar.tsx": $components_Avatar_Avatar,
    "./islands/components/Button/Button.tsx": $components_Button_Button,
    "./islands/components/ModalButton/ModalButton.tsx":
      $components_ModalButton_ModalButton,
    "./islands/components/NewEventModalButton/NewEventModalButton.tsx":
      $components_NewEventModalButton_NewEventModalButton,
    "./islands/components/Pills/PillTick.tsx": $components_Pills_PillTick,
    "./islands/components/Pills/Pills.tsx": $components_Pills_Pills,
    "./islands/components/SelectInput/SelectInput.tsx":
      $components_SelectInput_SelectInput,
    "./islands/components/Tag/Tag.tsx": $components_Tag_Tag,
    "./islands/components/TextInput/TextInput.tsx":
      $components_TextInput_TextInput,
    "./islands/components/WalletButton/WalletButton.tsx":
      $components_WalletButton_WalletButton,
    "./islands/pages/Markets/MarketCard.tsx": $pages_Markets_MarketCard,
    "./islands/pages/Markets/Markets.tsx": $pages_Markets_Markets,
    "./islands/pages/Markets/formatCurrencyShort.ts":
      $pages_Markets_formatCurrencyShort,
    "./islands/pages/Portfolio/Portfolio.tsx": $pages_Portfolio_Portfolio,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
